name: Copy WAV Files from DCS-Datamine-Raw-Files and Update wav_list.json

on:
  workflow_dispatch: # Manual trigger

jobs:
  copy-wav-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (F-4E-RWR-PRF-Library)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git credentials for cloning source
        run: |
          git config --global url."https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Clone source repo (DCS-Datamine-Raw-Files)
        run: |
          git clone --depth=1 https://github.com/OfficialDSplayer/DCS-Datamine-Raw-Files.git source-repo

      - name: Copy .wav files and Save Commit Message
        run: |
          # Capture latest commit message BEFORE deleting source-repo
          cd source-repo
          LATEST_COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          cd ..

          echo "$LATEST_COMMIT_MSG" > latest_commit_msg.txt

          # Clean old WAV files
          rm -rf imported_wavs
          mkdir -p imported_wavs

          # Copy WAV files
          cp source-repo/Mods/aircraft/F-4E/Sounds/Effects/Aircrafts/RHAW/radars/*.wav imported_wavs/

          # Remove the source-repo to avoid untracked files
          rm -rf source-repo

      - name: Generate wav_list.json
        run: |
          echo "[" > wav_list.json
          find imported_wavs -name "*.wav" | sort | sed 's/^/"/;s/$/",/' >> wav_list.json
          sed -i '$ s/,$//' wav_list.json # Remove trailing comma
          echo "]" >> wav_list.json


      - name: Commit and Push Changes
        run: |
          # Load latest commit message
          LATEST_COMMIT_MSG=$(cat latest_commit_msg.txt)

          # Get current UTC timestamp
          COMMIT_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Create final commit message
          FINAL_COMMIT_MSG="$LATEST_COMMIT_MSG (Synced on $COMMIT_TIMESTAMP)"

          echo "Final commit message will be: $FINAL_COMMIT_MSG"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add imported_wavs wav_list.json

          if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
          else
            git commit -m "$FINAL_COMMIT_MSG"
            git push
          fi
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
