name: Copy WAV Files from DCS-Datamine-Raw-Files

on:
  workflow_dispatch: # Manual trigger

jobs:
  copy-wav-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (F-4E-RWR-PRF-Library)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git credentials for cloning source
        run: |
          git config --global url."https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Clone source repo (DCS-Datamine-Raw-Files)
        run: |
          git clone --depth=1 https://github.com/OfficialDSplayer/DCS-Datamine-Raw-Files.git source-repo

      - name: Clean old WAV files
        run: |
          rm -rf imported_wavs
          mkdir -p imported_wavs

      - name: Copy .wav files
        run: |
          cp source-repo/Mods/aircraft/F-4E/Sounds/Effects/Aircrafts/RHAW/radars/*.wav imported_wavs/
          # Immediately remove the source repo to avoid git issues
          rm -rf source-repo

      - name: Commit and Push Changes
        run: |
          # Get latest commit message from DCS-Datamine-Raw-Files
          LATEST_COMMIT_MSG=$(git log -1 --pretty=format:"%s" --source-repo)

          # Get current UTC timestamp
          COMMIT_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Create final commit message
          FINAL_COMMIT_MSG="$LATEST_COMMIT_MSG (Synced on $COMMIT_TIMESTAMP)"

          echo "Final commit message will be: $FINAL_COMMIT_MSG"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add imported_wavs

          if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
          else
            git commit -m "$FINAL_COMMIT_MSG"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.secrets.PERSONAL_ACCESS_TOKEN }}
